version: '3.8'

services:
  # PostgreSQL database for ichiran
  postgres:
    image: postgres:15-alpine
    container_name: ichiran-postgres
    environment:
      POSTGRES_DB: ichiran
      POSTGRES_USER: ichiran
      POSTGRES_PASSWORD: ichiran_password
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - ichiran-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ichiran -d ichiran"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Ichiran service
  ichiran:
    build:
      context: .
      dockerfile: Dockerfile.ichiran
    container_name: ichiran-container
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=ichiran
      - DB_USER=ichiran
      - DB_PASSWORD=ichiran_password
    volumes:
      - ichiran_data:/app/data
    networks:
      - ichiran-network
    healthcheck:
      test: ["CMD-SHELL", "ichiran-cli --help || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Go API Server
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-ichiran-api
    depends_on:
      ichiran:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - GIN_MODE=release
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ichiran-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: ichiran-nginx
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    networks:
      - ichiran-network
    restart: unless-stopped

volumes:
  postgres_data:
  ichiran_data:

networks:
  ichiran-network:
    driver: bridge
